name: masterstudy_app
description: MasterStudy App by Stylemix

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.5+65

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #networking
  http: ^1.3.0
  dio: ^5.8.0+1
  rxdart: ^0.28.0
  get_it: ^8.0.3

  #stateManagement
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  #di
  inject:
    path: ./inject.dart/package/inject

  #utils
  meta: ^1.1.6
  equatable: ^2.0.5
  json_annotation: ^4.4.0
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  overlay_support: ^2.1.0
  image_downloader: ^0.31.0
  intl: ^0.20.2
  flutter_inappwebview: ^6.1.5

  #googleSignIn
  google_sign_in: ^6.0.2

  #facebookSignIn
  flutter_facebook_auth: ^7.1.1

  #utils
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.3
  external_path: ^2.2.0

  #Firebase
  firebase_crashlytics: ^4.3.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  #ui
  cupertino_icons: ^1.0.3
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_html: ^3.0.0
  file_picker: ^9.2.0
  video_player: ^2.3.0
  chewie: ^1.0.0
  font_awesome_flutter: ^10.3.0
  youtube_player_flutter: ^9.1.1
  vimeo_player_flutter: ^0.1.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  html_unescape: ^2.0.0
  page_transition: ^2.0.9
  in_app_purchase: ^3.0.8
  image: ^4.5.3
  fluttertoast: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  json_serializable: ^6.1.4

  inject_generator:
    path: ./inject.dart/package/inject_generator

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/raster/
    - assets/images/vector/
    - assets/localization/
