name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.20.1
