name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  code_builder: ^4.1.0
  collection: ^1.14.7
  dart_style: ^2.2.2
  logging: ^1.0.2
  meta: ^1.1.2
  path: ^1.5.1
  quiver: ^3.0.1+1
  stack_trace: ^1.9.2

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  inject:
    path: ../inject
  test: ^1.20.1
